services:
  - type: web
    name: esmeralda-frontend
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: VITE_API_URL
        value: https://proyecto-esmeralda.onrender.com